"""add returned_date column to user_books

Revision ID: 0e6caad6ea69
Revises: d4d581c2a7d1
Create Date: 2026-07-22 14:38:00.593077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e6caad6ea69'
down_revision: Union[str, None] = 'd4d581c2a7d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_books', sa.Column('returned_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_books', 'returned_date')
    # ### end Alembic commands ###
